# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GkXWFaYukEBw3LsruzcQwJWwrow1FyWm
"""

# Printing Hello World!

print ("Hello World!");