# -*- coding: utf-8 -*-
"""Print positive numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynw_NpEKgLU5pjJaP-IhrhHIvRJQyt1j
"""

# Printing positive numbers

def print_positive_numbers(numbers):
  positive_numbers = []

  # Iterate through each number in list
  for num in numbers:
    # To check that the number is positive
    if num > 0:
      # If the number is positive, append it to positive_numbers list
      positive_numbers.append(num)

  # Print positive numbers
  print(positive_numbers)

# Input list
list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

# Output for list1
print_positive_numbers(list1)

# Output for list2
print_positive_numbers(list2)